In [25]:
import torch
import torch.nn as nn

class Model(nn.Module):
    def __init__(self,num_features):

        super().__init__()
        self.network=nn.Sequential(        # Sequintial Container
            nn.Linear(num_features,3),
            nn.ReLU(),
            nn.Linear(3,1),
            nn.Sigmoid()
        )


    def forward(self,features):

          out = self.network(features)
          return out

In [26]:
# create dataet
features = torch.rand(10,5)

# create model
model =  Model(features.shape[1])

#call model for forward pass
model(features)

tensor([[0.4077],
        [0.4131],
        [0.4273],
        [0.4373],
        [0.4149],
        [0.4216],
        [0.4463],
        [0.4580],
        [0.4452],
        [0.4549]], grad_fn=<SigmoidBackward0>)

In [28]:
# show the weights and bias of the first linear layer
print("Weights of linear1:")
print(model.network[0].weight)
print("Bias of linear1:")
print(model.network[0].bias)

# show the weights and bias of the second linear layer
print("\nWeights of linear2:")
print(model.network[2].weight)
print("Bias of linear2:")
print(model.network[2].bias)

Weights of linear1:
Parameter containing:
tensor([[-0.1373, -0.3709, -0.3196, -0.0447, -0.1163],
        [ 0.3546, -0.0371,  0.2698, -0.4450,  0.0196],
        [ 0.2393, -0.3820,  0.3596,  0.4209, -0.0733]], requires_grad=True)
Bias of linear1:
Parameter containing:
tensor([ 0.0851,  0.2003, -0.0359], requires_grad=True)

Weights of linear2:
Parameter containing:
tensor([[ 0.4705,  0.2842, -0.1852]], requires_grad=True)
Bias of linear2:
Parameter containing:
tensor([-0.3101], requires_grad=True)


In [21]:
!pip install torchinfo

In [29]:
# if you want to see the Structure
from torchinfo import summary

summary(model,input_size=(10,5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Sequential: 1-1                        [10, 1]                   --
│    └─Linear: 2-1                       [10, 3]                   18
│    └─ReLU: 2-2                         [10, 3]                   --
│    └─Linear: 2-3                       [10, 1]                   4
│    └─Sigmoid: 2-4                      [10, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00