In [84]:
import torch

if torch.cuda.is_available():
  print('cuda is available!')
  print(f'using GPU: {torch.cuda.get_device_name(0)}')
else:
  print('GPU is not available.Using CPU')

cuda is available!
using GPU: Tesla T4


Creating Tensor

In [85]:
#using empty
a= torch.empty(2,3)


In [86]:
#using type
type(a)

torch.Tensor

In [87]:
#using zeros
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [88]:
#using ones
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [89]:
#using random
torch.rand(2,3)

tensor([[0.3206, 0.9753, 0.7582],
        [0.6688, 0.2651, 0.2336]])

In [90]:
#using manual_seed
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [91]:
#using tensor
torch.tensor([[1,2,3],[2,3,4]])

tensor([[1, 2, 3],
        [2, 3, 4]])

In [92]:
#other ways

#arrange
print('using arrange->',torch.arange(0,10,2))

#using linspace
print('using linspace->',torch.linspace(0,10,10))

#using eye
print('using eye ->',torch.eye(5))

#using full
print('using full->',torch.full((2,2),5))

using arrange-> tensor([0, 2, 4, 6, 8])
using linspace-> tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])
using eye -> tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
using full-> tensor([[5, 5],
        [5, 5]])


Tensor Shape

In [93]:
x = torch.tensor([[1,2,3],[2,3,4]], dtype=torch.float)
x

tensor([[1., 2., 3.],
        [2., 3., 4.]])

In [94]:
x.shape

torch.Size([2, 3])

if we want to create tensor of same shape then we can usse following methods


In [95]:
torch.empty_like(x)

tensor([[1.4163e-18, 0.0000e+00, 3.1844e-17],
        [0.0000e+00, 1.1210e-43, 0.0000e+00]])

In [96]:
torch.zeros_like(x)


tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [97]:
torch.ones_like(x)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [98]:
torch.rand_like(x,dtype=torch.float32)

tensor([[0.2627, 0.0428, 0.2080],
        [0.1180, 0.1217, 0.7356]])

Tensor Data Type

In [99]:
#find the data type
x.dtype

torch.float32

In [100]:
#assign the data type
torch.tensor([1.0,22.0,3.0],dtype=torch.int32)

tensor([ 1, 22,  3], dtype=torch.int32)

In [101]:
torch.tensor([1,2,3],dtype=torch.float64)

tensor([1., 2., 3.], dtype=torch.float64)

In [102]:
#using to()
x.to(torch.float32)

tensor([[1., 2., 3.],
        [2., 3., 4.]])

Mathematical Operations

1.Scalar Operataion

In [103]:
x = torch.rand(2,3)
x

tensor([[0.7118, 0.7876, 0.4183],
        [0.9014, 0.9969, 0.7565]])

In [104]:
# addition
x+2
# subtraction
x-2
#multiplication
x*2
#division
x/2
#int division
(x*100)//3
#mod
(x*100)//3 % 2
#power
x**2

tensor([[0.5066, 0.6203, 0.1750],
        [0.8125, 0.9938, 0.5723]])

2.Element wise operation

In [105]:
a = torch.rand(2,3)
b = torch.rand(2,3)
print(a)
print(b)


tensor([[0.2239, 0.3023, 0.1784],
        [0.8238, 0.5557, 0.9770]])
tensor([[0.4440, 0.9478, 0.7445],
        [0.4892, 0.2426, 0.7003]])


In [106]:
# add
a+b
# sub
a-b
# multiply
a*b
# division
a/b
#power
a**b
#mod
a % b


tensor([[0.2239, 0.3023, 0.1784],
        [0.3346, 0.0706, 0.2767]])

In [107]:
 c = torch.tensor([1,-2,3,-4])
 c

tensor([ 1, -2,  3, -4])

In [108]:
# abs
torch.abs(c)

tensor([1, 2, 3, 4])

In [109]:
# negative
torch.neg((c))

tensor([-1,  2, -3,  4])

In [110]:

d= torch.tensor([1.9,2.3,3.7,4.6])


In [111]:
torch.round(d)

tensor([2., 2., 4., 5.])

In [112]:
# ceil
torch.ceil(d)

tensor([2., 3., 4., 5.])

In [113]:
# floor
torch.floor(d)

tensor([1., 2., 3., 4.])

In [114]:
# clamp
torch.clamp(d,min=2,max=3)

tensor([2.0000, 2.3000, 3.0000, 3.0000])

3.Reduction Opertation


In [115]:
e = torch.randint(size=(2,3),low=0,high=10,dtype =torch.float32)
e

tensor([[7., 0., 0.],
        [9., 5., 7.]])

In [116]:
# sum
torch.sum(e)
# sum along column
torch.sum(e,dim=0)
#sum along rows
torch.sum(e,dim=1)


tensor([ 7., 21.])

In [117]:
# mean
torch.mean(e)
# mean along colum
torch.mean(e,dim=0)

tensor([8.0000, 2.5000, 3.5000])

In [118]:
# median
torch.median(e)

tensor(5.)

In [119]:
# max and min
torch.min(e)
torch.max(e)

tensor(9.)

In [120]:
# product
torch.prod(e)

tensor(0.)

In [121]:
# standart deviation
torch.std(e)

tensor(3.8297)

In [122]:
 # varaiance
 torch.var((e))

tensor(14.6667)

In [123]:
# argmax
torch.argmax(e)

tensor(3)

In [124]:
# argmin
torch.argmin(e)

tensor(1)

Matrix Operation


In [125]:
f = torch.randint(size=(2,3),low=0,high=10)
g = torch.randint(size=(3,2),low=0,high=10)
print(f)
print(g)

tensor([[3, 9, 4],
        [0, 5, 7]])
tensor([[5, 9],
        [9, 7],
        [5, 9]])


In [126]:
# matix multiplication
torch.matmul(f,g)

tensor([[116, 126],
        [ 80,  98]])

In [127]:
# dot product
vector1 = torch.tensor([1,2])
vector2 = torch.tensor([3,4])

torch.dot(vector1,vector2)

tensor(11)

In [128]:
# transpose
torch.transpose(f,0,1)

tensor([[3, 0],
        [9, 5],
        [4, 7]])

In [129]:
h =  torch.randint(size=(3,3),low=0,high=10,dtype = torch.float32)
print(h)


tensor([[8., 9., 7.],
        [9., 2., 6.],
        [7., 7., 8.]])


In [130]:
# determinant
torch.det(h)

tensor(-135.0000)

In [131]:
# inverse

torch.inverse(h)

tensor([[ 0.1926,  0.1704, -0.2963],
        [ 0.2222, -0.1111, -0.1111],
        [-0.3630, -0.0519,  0.4815]])

Comparison Operation

In [132]:
i = torch.randint(size=(2,3),low=0,high=10)
j = torch.randint(size=(2,3),low=0,high=10)
print(i)
print(j)

tensor([[3, 6, 1],
        [5, 5, 0]])
tensor([[4, 3, 8],
        [8, 3, 3]])


In [133]:
# greater than
i > j

# less than
i < j

# not equal to
i != j

# greater than equal to
i >= j

# less than equal to

i <= j

tensor([[ True, False,  True],
        [ True, False,  True]])

Special Funtion


In [134]:
k = torch.randint(size=(2,3),low=0,high=10,dtype = torch.float64)
k

tensor([[5., 0., 6.],
        [4., 0., 8.]], dtype=torch.float64)

In [135]:
# log
torch.log(k)

#exp
torch.exp(k)

# sqrt
torch.sqrt(k)

# sigmoid
torch.sigmoid(k)

# tanh
torch.tanh(k)

# softmax
torch.softmax(k,dim=1)

# relu
torch.relu(k)

tensor([[5., 0., 6.],
        [4., 0., 8.]], dtype=torch.float64)

Inplace Operation


In [136]:
m = torch.rand(2,3)
n = torch.rand(2,3)
print(m)
print(n)

tensor([[0.0453, 0.9798, 0.5548],
        [0.6868, 0.4920, 0.0748]])
tensor([[0.9605, 0.3271, 0.0103],
        [0.9516, 0.2855, 0.2324]])


In [137]:
m + n

tensor([[1.0058, 1.3069, 0.5650],
        [1.6384, 0.7776, 0.3072]])

In [138]:
m.add_(n)

tensor([[1.0058, 1.3069, 0.5650],
        [1.6384, 0.7776, 0.3072]])

In [139]:
m


tensor([[1.0058, 1.3069, 0.5650],
        [1.6384, 0.7776, 0.3072]])

In [140]:
n

tensor([[0.9605, 0.3271, 0.0103],
        [0.9516, 0.2855, 0.2324]])

In [141]:
torch.relu(m)

tensor([[1.0058, 1.3069, 0.5650],
        [1.6384, 0.7776, 0.3072]])

In [142]:
m.relu_()

tensor([[1.0058, 1.3069, 0.5650],
        [1.6384, 0.7776, 0.3072]])

Copying Tensor


In [143]:
a =  torch.rand(2,3)
a

tensor([[0.9141, 0.7668, 0.1659],
        [0.4393, 0.2243, 0.8935]])

In [145]:
b = a
b

tensor([[0.9141, 0.7668, 0.1659],
        [0.4393, 0.2243, 0.8935]])

In [146]:
a[0][0]=0
a

tensor([[0.0000, 0.7668, 0.1659],
        [0.4393, 0.2243, 0.8935]])

In [147]:
b

tensor([[0.0000, 0.7668, 0.1659],
        [0.4393, 0.2243, 0.8935]])

In [148]:
id(a)


133538402637920

In [149]:
id(b)

133538402637920

In [150]:
b = a.clone()

In [151]:
a

tensor([[0.0000, 0.7668, 0.1659],
        [0.4393, 0.2243, 0.8935]])

In [152]:
b

tensor([[0.0000, 0.7668, 0.1659],
        [0.4393, 0.2243, 0.8935]])

In [153]:
a[0][0]=100

In [154]:
b

tensor([[0.0000, 0.7668, 0.1659],
        [0.4393, 0.2243, 0.8935]])

In [155]:
a

tensor([[100.0000,   0.7668,   0.1659],
        [  0.4393,   0.2243,   0.8935]])

In [157]:
id(a)


133538402637920

In [158]:
id(b)

133537908336080

Tensor Operations on GPU

In [159]:
torch.cuda.is_available()

True

In [160]:
device = torch.device('cuda')

In [161]:
# creating a new tensor on GPU
torch.rand((2,3),device = device)

tensor([[0.3563, 0.0303, 0.7088],
        [0.2009, 0.0224, 0.9896]], device='cuda:0')

In [164]:
# moving an existing tensor to GPU
a = torch.rand((2,3))
b = a.to(device)


In [165]:
b + 5

tensor([[5.9157, 5.3079, 5.6269],
        [5.8277, 5.6594, 5.0887]], device='cuda:0')

Comparing Difference in CPU and GPU to run the same size tensor

In [167]:
import time

# Define the size of the matrices
size = 1000  # Lagre size for performance comparison

# creating random matrices on CPU
martix_cpu1 = torch.rand((size,size))
martix_cpu2 = torch.rand((size,size))

# measures on CPU
start_time = time.time()
result_cpu = torch.matmul(martix_cpu1,martix_cpu2) # matrix multiplication on CPU
end_time = time.time()
cpu_time = end_time - start_time

print(f'Time on CPU: { cpu_time:.4f} seconds')

# move matrices to GPU
martix_gpu1 = martix_cpu1.to('cuda')
martix_gpu2 = martix_cpu2.to('cuda')


# measures on GPU
start_time = time.time()
result_gpu = torch.matmul(martix_gpu1,martix_gpu2) # matix multiplication on GPU
torch.cuda.synchronize() # ensure all GPU are complete
end_time = time.time()
gpu_time = end_time - start_time

print(f'Time on GPU: { gpu_time:.4f} seconds')

# compare results
print('\nSpeedup (CPU time / GPU time):',cpu_time / gpu_time)

Time on CPU: 0.0274 seconds
Time on GPU: 0.0011 seconds

Speedup (CPU time / GPU time): 25.527790128946197


Reshaping tensor


In [169]:
r = torch.ones(4,4)
r


tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [170]:
# reshape
r.reshape(2,2,2,2)

tensor([[[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]],


        [[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]]])

In [171]:
# flatten
r.flatten()

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [172]:
s =  torch.rand(2,3,4)
s

tensor([[[0.2843, 0.3462, 0.0178, 0.4498],
         [0.3295, 0.5860, 0.8068, 0.5763],
         [0.1790, 0.3608, 0.5556, 0.5452]],

        [[0.4121, 0.3879, 0.8970, 0.0208],
         [0.5636, 0.3210, 0.4230, 0.3890],
         [0.6299, 0.8152, 0.5458, 0.7850]]])

In [175]:
# permutation
s.permute(2,0,1).shape

torch.Size([4, 2, 3])

In [181]:

# image size
x =  torch.rand(226,226,3)
x
# unsqueeze
x.unsqueeze(0).shape


torch.Size([1, 226, 226, 3])

In [182]:
# squeeze
x.unsqueeze(0).squeeze(0).shape

torch.Size([226, 226, 3])

Numpy and PyTorch

In [183]:
import numpy as np

In [185]:
v = torch.tensor([1,2,3])
v

tensor([1, 2, 3])

In [186]:
y = v.numpy()

In [190]:
y

array([1, 2, 3])

In [188]:
type(y)

numpy.ndarray

In [191]:
f = np.array([1,2,3])
f

array([1, 2, 3])

In [192]:
torch.from_numpy(f)

tensor([1, 2, 3])